# migrations/20250516_194652_insert_urldocument_documents.py


# Migración: insert_urldocument_documents
# Fecha de creación: 20250516_194652


def upgrade(cursor):
    # Aquí va el código para aplicar la migración
    queries = [
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=10BvJXuRn-diKbgAL9R2ROxOaaO4TQq9e' WHERE title = 'American Psycho'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1sUXWiy_DF7geBaw_pgeHfkU9NNIWeXD2' WHERE title = 'Arcanum ilimitado'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1SMxm3GUlwhCfkcSAfmwX9y9ETJDrv0h8' WHERE title = 'Battle Royale'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1pnhHSQEySm7JBkHmT9JZCiqMxytfvPuh' WHERE title = 'Elantris'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1h5g9GP1y45g0AdtkaX-s7SGVbiuu7sCf' WHERE title = 'Escuadrón'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1sOzM9NOUWbXSowFulcZ9v-IdjJ4iBHCy' WHERE title = 'Estelar'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1tPzV9naWF7x5q9O2winMQUQxWo_aSGmN' WHERE title = 'Citónica'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1MrSUChbYB5uc-mbUZNo4rTv4yl0gcsyq' WHERE title = 'Desafiante'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1EAvL3cZo-mf0IGgJlM3KSmd78L23OhAO' WHERE title = 'El camino de los reyes'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=16ouFRFkdHqyne9DQiC6xS1oQRlzXQQwX' WHERE title = 'Palabras Radiantes'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=11ROezEFaAKSPugGG8bxjdOu8HG6zewiz' WHERE title = 'Danzante del Filo'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1BkhVG25ER_GxFn9_8t-l7DCSv4eUJNF2' WHERE title = 'Juramentada'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1EYh1Nsh8YYmxf6QR1unwnAIA57bHGhsP' WHERE title = 'Esquirla del amanecer'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1tKNDzkWreBM9o0U0tIG4xD6r9PovXkJz' WHERE title = 'El ritmo de la guerra'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1h4decyPVRWpWvoXih1NKHhzfUmwfKuIM' WHERE title = 'El hombre iluminado'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1WKU9P65iFVC4TOgdK1-OAmyFiN_VvniM' WHERE title = 'Viento y Verdad'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1WmmS8Sn_cFxlu7gUldb2t0afZ8r5CTY1' WHERE title = '50 Sombras de Grey'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1mscjhlJwzwjI1WHkOcrOt5ns16iHhUwo' WHERE title = '50 Sombras más oscuras'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=17N0kqMpt0W5SceYZ-Sa-2h0g2nuI-yQm' WHERE title = '50 Sombras liberadas'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1-de3Fj7_hfLBv2pIGpjn7t-hf72uYAfS' WHERE title = '2001 Una odisea espacial'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1MqQFAtaEE5bVARL31dJg1s3MkZETPvwD' WHERE title = '2010 Odisea dos'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1JVqUvXFCFoLhu2WNq3qKaQGGrr4p12nT' WHERE title = '2061 Odisea tres'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1v8doRXqmZRi98pLHG_fk1JhbE5fIqEzO' WHERE title = '3001 Odisea final'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1YnQvMl4THOU6ODDaBZZwx9AtVV6x6CNW' WHERE title = 'El principio del fin'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1LavneCtositG594lhaElcLzucGOdE22X' WHERE title = 'Los dias oscuros'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1Nv4QvT7olsrigJd_BinBKNm3CT6mXYBr' WHERE title = 'La ira de los justos'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=17m--4PK7vZ3NfxW2kMUG4IAiQmW1DagF' WHERE title = 'Arena blanca'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1z7NgI16zdvrW6LqlvDxpYRqJ3r6nnLvg' WHERE title = 'Ascensión'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1XvalEPw29o0oG4M9Czv3WZiK0wS5Awsu' WHERE title = 'Asesinato en el Orient express'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1TAz_ZqlduJaXu-tH6xYXJGaWP3gd0Ylc' WHERE title = 'Juego de tronos'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1Y6rzzFo9KKUz5ipca_wJbU26hmAfsbAO' WHERE title = 'Choque de Reyes'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=11ebXmK8MFNIFsw58bV25qOp50iotJIec' WHERE title = 'Tormenta de espadas'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1eGyE8joKNtcOdHXbf3WaOMV2dwjARZLc' WHERE title = 'Festín de cuervos'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1f91PbU0aHCY_gOov5WeQQmQTv5LE9FQ8' WHERE title = 'Danza de Dragones'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1U7lG1z7g-sHWspA5aOvHMOad5vdktkfS' WHERE title = 'Carrie'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1_SXNHsD9Dzqs16QmNa8gaxjYYy476lr6' WHERE title = 'Cujo'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1IWYlonjP4ybVbEKnMeRLxE7-OOJCK9na' WHERE title = 'Déjame entrar'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=105Im6y2IqWZxEGirpIZkCZxD5kr6hQmr' WHERE title = 'Diario de una Ninfómana'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1J27lRMQjwxaKOePywKvAyO_0-_cMp4X7' WHERE title = 'Drácula'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1OCAIR_1Hrh4ZAuzAsRbxstfK46GH3jXJ' WHERE title = 'Dune'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1aRD0hJvths1sYqhK__jOQb17HIppPxi2' WHERE title = 'El mesías de Dune'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1qBeOgfFaznHMcReUmcHAmyKAkvLaCiN2' WHERE title = 'Hijos de Dune'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1rXf0dYX5ouyaxyrvtUP30N2X8HgMt0ZS' WHERE title = 'Dios emperador de Dune'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1a-VgP3mYSY7wTSu0lCs_pVHreGjBXVKV' WHERE title = 'Herejes de Dune'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1ErJ083eoastyXJgnmtsibdFZczJja9II' WHERE title = 'Casa capitular Dune'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1kzGOiHez0G9Ie91ZS0kxMBdUomK-l83L' WHERE title = 'Cazadores de Dune'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1rcQ7aPvZh1V99RUA00c71HzMhn-FStUE' WHERE title = 'Gusanos de arena de Dune'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1StH_o4wr0lND4AQmRzMyKeV7VvLqhj6b' WHERE title = 'El Aliento de los dioses'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1oesbwHzd7NHF6-OZcW6Ju3syuzemEmpz' WHERE title = 'El Alquimista'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1PunEQxBD_Ma2oC3hq_SQgxC0QtimrGY0' WHERE title = 'El cazador'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1Pz3557TemQahLGz_qazUMEotqnzg2YOy' WHERE title = 'La tormenta'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1utc3d2sA2iCPNWJ82UYY7BjpqXvWnk2P' WHERE title = 'El emperador'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1lK1oEpcxF7Tumqur9cbmPETlnGEXykfs' WHERE title = 'Ángeles y Demonios'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1_3fK0kn3MehAtMgjLHGctY8-hyJTFzfU' WHERE title = 'El código Da Vinci'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=14bCHCo-Rs2nYtCEyy_9KpdKDDTVWXebA' WHERE title = 'El símbolo perdido'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1pV6oDjR7taMM21jIcclpdgWg3VOBrXSz' WHERE title = 'Inferno'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=19S8kCXE-lfQaP5LbnVRZlMVDHG35nXFG' WHERE title = 'Origen'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1Eo0fCr5-QP-HHEpPhbH9Ca9drLPB2SH4' WHERE title = 'El cuento de la criada'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1nLJIFLehSLkeAzKt-W-vvkvPeOohX77j' WHERE title = 'El exorcista'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1vXLIOkrJ_MNZuFCNsicIR0L8SFbVRAbW' WHERE title = 'El juego de Ender'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1Aw0uD7YP138bKm7vBoOxgNF-J99i-SmY' WHERE title = 'La voz de los muertos'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1l5Fq4XJSqykoOJMNvbmbZdbRLO5JndFS' WHERE title = 'Ender el xenocida'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1SxKzRWbxkbmPtO_GGHkF0rVVyolzfFPf' WHERE title = 'Hijos de la mente'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1TWshXUKSEyVIxNtsazRrYSGZA8W11rBn' WHERE title = 'Ender en el exilio'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1G8LnDdXdgvx8B-f7n3DHlRHAFoSskfJq' WHERE title = 'El nuevo Kamasutra ilustrado'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1aDOPbj6ZDPePVpyCxxZJpQ9Ou8YqcvdN' WHERE title = 'El psicoanalista'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1SV0tVJF-kVR2Q97_UXUA25z8Mfcuv3si' WHERE title = 'Jaque al psicoanalista'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1R7iet6xTEqwEAfWMxkwE39-O_WxeMwWb' WHERE title = 'El psicoanalista en la mira'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1NsDAvUBZuklJX1Kj1XveHBQXBhWL0cnA' WHERE title = 'El resplandor'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1jBY1u1ZwBQdGqvLkx5dbjuYtyTAN77Nw' WHERE title = 'Doctor sueño'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1L4NDeAUAmFnFHG2Ldk1Qy3omiP1a_j3e' WHERE title = 'El señor de los anillos'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1dAS24Kbh3S8dnA9bPp9sQPWFimc7OgFX' WHERE title = 'La comunidad del anillo'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1tJ96GXWlYY_WTWMMnEMrsIiImhKlySXn' WHERE title = 'Las dos torres'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1N3keTVWGlvtzUAjoZugpdm4jOUXGM0yb' WHERE title = 'El retorno del rey'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1Ap4wF8G756Ieca3lSpehQhBVtfxTd1SZ' WHERE title = 'El show de las marionetas'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1Sdb0p0Y7TRfWJrTwxlVf5TBJgBlBpHAB' WHERE title = 'Hannibal el origen del mal'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1LYhmk4v1EbUOC-GjNFZoie9wMB8OKLO5' WHERE title = 'Dragón Rojo'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1IBgA7c5ndCh10R5yeCbka7dYAwERQMXe' WHERE title = 'El silencio de los corderos'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1uJ3umfspR-Luc5Ymg2nCEi7gt9LG8D-R' WHERE title = 'Hannibal'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=18MCYoktYwBLu6G1bqeIJcTFTd26TaOp8' WHERE title = 'La defensa del Eliseo'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1vecC8vTjcU4KC3Q9tnToDingssz9wUEc' WHERE title = 'En las montañas de la locura'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1mAX0h3RhYJiL5F49QxP6wRKXjiINWuy2' WHERE title = 'Fahreinheit 451'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1LXduLfxd51_KxlA--afxIpM8-a5hRzhm' WHERE title = 'Frankenstein'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1i8-BWvBxd_EjP6Heir4g8xgGQpxNml0b' WHERE title = 'Guerra mundial Z'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1CIKEDNDCCSGGpnVRSxL0vjD_6madCY6i' WHERE title = 'La Cala'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1uOHmd4Oluiv_lqYF0fXJkYxVY26B41CH' WHERE title = 'Haunting Adeline: Nunca te dejaré'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1jg8WDSZxUYoBNhdPpXlxfii3eUDFUmTJ' WHERE title = 'Te encontraré'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1YoHhJF4KepKsJpcBlp9j0ZuJiBeCE9Lr' WHERE title = 'La biblia contada para escépticos'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1AGmhHWzm2Cqky0aPBjs42zmhA5Sm9Wzk' WHERE title = 'La cúpula'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=17WK2iCXJYPAPOnSp0xrbSagID-bmnOeW' WHERE title = 'La enfermera de Auschwitz'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=16H0f3zEq0-3D_alRhGqBCRvy-io2jxzP' WHERE title = 'La guerra de los mundos'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1KXM51_47yQkR2D8SZaahC8OYivhfxCQw' WHERE title = 'La llamada de Cthulhu'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1qd-9mgSk_mXuFSEZAtNSGf0eHxJaL_Ng' WHERE title = 'La historia interminable'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1Mgxh5TCIiT1HNYO5-C1JAH6EyF3ynvE1' WHERE title = 'Lascivia Pecados placenteros'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1R77N5LAR7GUdmplQEm3wz3JrOTbiQ_vT' WHERE title = 'Lolita'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1PEmCNxozyd6R5OyfQCvj2yHivBT1-EyM' WHERE title = 'Las edades de Lulú'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1NZOB4C2hiyoOvSKjLHWSEl-4GvdM3diE' WHERE title = 'Moby Dick'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1jnDNEfhIHqnsytKHHmu00utKHS2cwmQD' WHERE title = 'La tapadera'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1kzhUN3CEwJoWHhrqbNldTDpFNdD1niTN' WHERE title = 'El intercambio'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1FydCzSdy03BV6xIO94PbUdllWw4LAL9T' WHERE title = 'Soy Leyenda'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=18FDO23XbzPrCSRQ67T5Sum27m2dc_vY8' WHERE title = 'Trenza del Mar esmeralda'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1H0ZIk2ngHyTNApl9__PlOAYhv4rei8Qr' WHERE title = 'Un crimen invisible'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1SqJdje56fjHpqpBs4PPEaT2qVRC9ScHY' WHERE title = 'Un crimen imaginado'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1uO2GgTtM89tfP-bjEl_UG9H-UgBobmXH' WHERE title = 'Un crimen contratado'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1FKeqnFQgqHB7ufFl1_JuA31z4SljKuQZ' WHERE title = 'Un crimen pasional'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1MBrXyNCDFmNNC5v9eu2dHJZsb_ezya76' WHERE title = 'Un crimen prescrito'",
        "UPDATE `documents` SET url_document = '' WHERE title = 'Un crimen vengado'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1SgU8iVVgr4x86V2Wy9ppEjhvPnsPfg6G' WHERE title = 'Susurros sensuales'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1pB2iJDdrKpDw0KsUVtP3Mr6lyX8A1bQC' WHERE title = 'Yo, robot'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=15erKAl3ozSiXJAnjTvUrHyf4KZoNn2tW' WHERE title = 'Bóvedas de acero'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1qbvUn0xz95nvUCPi9rv7CHI-K4RG9c_s' WHERE title = 'El Sol desnudo'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1QzTUx2WHwquwnbmrSYuI_xmmHvGsxvbt' WHERE title = 'Los Robots del amanecer'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=15BMVJDI1qBYzdCM_PnY4mm7SM2rvJbQe' WHERE title = 'Robots e imperio'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1xFhFsm8trMZBzS28zT_GEx9JaShmBBMJ' WHERE title = 'Yumi y el pintor de pesadillas'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1TpkmSw92vr2k3wxS1TJFM7X__kzn5g8X' WHERE title = 'La rueda del tiempo'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1XnGIZqy3vNhKlJDb58zq6gQUstUr8vgI' WHERE title = 'El Imperio Final'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1dCRheyq9l4Hty6tKwR2lfWDfJsUsJp-K' WHERE title = 'El pozo de ascensión'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1MIP_0UU_jq2lp5beUb-aLxclOV-v9Q-T' WHERE title = 'El Héroe de las eras'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1ZqbvTzeGOl6o38hGiEnF5yu5AR38EPo0' WHERE title = 'Aleación de ley'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1Q2yHsintQWqXsrZSebnI4yYsSg7w1JZ9' WHERE title = 'Sombras de identidad'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1smq9tpczVo42RZ9QVgW2JujAxsf79fga' WHERE title = 'Brazales de duelo'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1eXMJ-47M6HLoHIp9npBKiT4VGiVfe1xk' WHERE title = 'Historia secreta'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1mR7t0b0hV_sxb2gek0S65SvgZ6_uvNXD' WHERE title = 'El metal perdido'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1pqiUtBMf4YQ4pWwGzPwV4KqRmlkH2E5J' WHERE title = 'Pídeme lo que quieras'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1y1mXFud0wBuCrE1Dx-cXIxnq1VuGgPiQ' WHERE title = 'Pídeme lo que quieras, ahora y siempre'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1EAxKE722FZk2GDUbWpzpeW20aRisRP_3' WHERE title = 'Pídeme lo que quieras o déjame'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1TzT05pwnGa2ZhoCuZJCdxIEyDgWtDlMB' WHERE title = 'Pídeme lo que quieras y yo te lo daré'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1MrybIL2b8Tf0ZpmEwsHwfMLwgH-NB9Tx' WHERE title = 'La chica del tren'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1V1MZwd6Sx4Nj3t1jcgl8cb4yt1FlBz3a' WHERE title = 'Sistemas críticos'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1x4W0BMCL9j-v7ARKFy95HiynEM4BPJlh' WHERE title = 'Condición artificial'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=18QSxrNrOZwxstejm8UIBqT2TohuyTXWb' WHERE title = 'Harry Potter y la piedra filosofal'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1-2Mdb1cu8NWKkccauyGAASz0zQ1atjuO' WHERE title = 'Harry Potter y la cámara secreta'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1OPPNqaT4o3neZM7pgv9ODxq_Dbl_QK81' WHERE title = 'Harry Potter y el prisionero de Azkaban'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=11P5lmrcg6YhRH_41oRspK02lE-5ZH9wI' WHERE title = 'Harry Potter y el cáliz de fuego'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=185tYLqcp_R3K2BiNLO5NQoggeQQeZ4rE' WHERE title = 'Harry Potter y la orden del Fénix'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1yDKzoARsjuqZFvFMLvFJ0pFyauiR-Z0E' WHERE title = 'Harry Potter y el misterio del príncipe'",
        "UPDATE `documents` SET url_document = 'https://drive.google.com/uc?id=1YYIVHczyagwNsSJeRTlsdZQpAtFwjU6e' WHERE title = 'Harry Potter y las reliquias de la muerte'",
    ]

    for query in queries:
        cursor.execute(query)
    pass


def downgrade(cursor):
    # Aquí va el código para revertir la migración
    cursor.execute()
    pass
