# migrations/20250519_164920_insert_urlimage_documents.py


# Migración: insert_urlimage_documents
# Fecha de creación: 20250519_164920

def upgrade(cursor):
    # Aquí va el código para aplicar la migración
    queries = [
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1U9SCEi5ivANkbPyNCCktUuPp4CzbOoL-' WHERE title = 'American Psycho'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1mZF9eW1KzRgqdq5cREcgFJTmHIaOI7CB' WHERE title = 'Arcanum ilimitado'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1nBPzgDMelB2Knx-S2Fpb5GXjEzVTnTES' WHERE title = 'Battle Royale'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1eNDfrmXy8nU4xym6eAtBL3ZYyFsF5hj0' WHERE title = 'Elantris'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1YwXoqd-pFH_ELkvBMzwTXtbkWhw1VMB2' WHERE title = 'Escuadrón'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1ZPEPY1gATqadKsrAoG33LZDzrPpGkAU_' WHERE title = 'Estelar'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=183qZ1xCwKA42mhxFqxYdeSJ2l9QMuPR2' WHERE title = 'Citónica'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1b1qoiMqs0Tr-D1Q6iESauzQ2I47peBFN' WHERE title = 'Desafiante'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1DCYBjUd9zL-xy3LooNgwQ25CpXNjNMOk' WHERE title = 'El camino de los reyes'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1I6CBwFXl8Ye3UE5qOiHesayGX-MWzzeG' WHERE title = 'Palabras Radiantes'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1L0bUvDpF1r3fXbY-LkNNwFcLIf-ArAzw' WHERE title = 'Danzante del Filo'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1P_FYINkKy_Psw5rjhIXef1KJF9UoMFdq' WHERE title = 'Juramentada'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=175zDZYFGd6hbGtpjC6IUQDQhZihrnSDD' WHERE title = 'Esquirla del amanecer'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=17qgq7fuddmoVY3ZX09s7GCHRPxSMnIEf' WHERE title = 'El ritmo de la guerra'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=19uvlSKf6UzM6INkFdZSQsnI6H6QtIX89' WHERE title = 'El hombre iluminado'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1UeG6rnjp3n1PxrA8ekVI4_4nyM_fsTqk' WHERE title = 'Viento y Verdad'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=12YjVR6y2p5oaBmhvheP_ZI1DAW6AUnKd' WHERE title = '50 Sombras de Grey'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1emLmkNn_4SDCSLAJKEtmxD7Cj6SC7iLa' WHERE title = '50 Sombras más oscuras'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1TGf5Mg2Bq1DqdkQCi29e5d1l3e6hVcfs' WHERE title = '50 Sombras liberadas'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1simQBy7NyGPDBQfOZ335TIYQC7GqyKHC' WHERE title = '2001 Una odisea espacial'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1tcgKwmNDuuuT_Kt73btuKAfvD9cdnpbZ' WHERE title = '2010 Odisea dos'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1LdQuGmwIquDBjL7EKvHh8FuRESrTQtf_' WHERE title = '2061 Odisea tres'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1Kfwm_YRnmdzueWFUTf_WSFywPV4pIZQM' WHERE title = '3001 Odisea final'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1R0x3K21R1SOsV6pw7XT-DjjwV0O78p0z' WHERE title = 'El principio del fin'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1qOF0M5UmvPtvtAu1t8NTkGdzkNEGEVdi' WHERE title = 'Los dias oscuros'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=14TDSV79a8-nVAaN5Kuq6Bl2TQF-pFdZ7' WHERE title = 'La ira de los justos'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1zNuFAuIy3Bqhyi97oZa1YjVzPW4CT41b' WHERE title = 'Arena blanca'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1RZ8i0XSI4m47yaVgtskN866gnke8zd7F' WHERE title = 'Ascensión'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1hr8Yjdxjg6uv_db97JiEJ-TfvzmtUu7S' WHERE title = 'Asesinato en el Orient express'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1IV3xV0vxq4yR_U7oyeS5CbC2oWnpo4Co' WHERE title = 'Juego de tronos'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1KGGpGMhxkg8pVA2j-19qn_Jd401zzG4x' WHERE title = 'Choque de Reyes'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1Loryld3kOZke0OYp3iyi9VgBN2FA0IsM' WHERE title = 'Tormenta de espadas'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1xrjlsdWfEgUsyGO9jkjyanE7EyKB7Wuq' WHERE title = 'Festín de cuervos'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=13mtGO-rXMbixRS-81c17Y1Xy8qa0TLO-' WHERE title = 'Danza de Dragones'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1M_R3ESy9BetEjmSL50oCgGHq3fzlwS28' WHERE title = 'Carrie'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1XCkOcXaxh16Fn_69UDNLIJtt0LmZ5kol' WHERE title = 'Cujo'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1VGTvnqBFNKg2F-7s9LOP6c-jAcUfehnb' WHERE title = 'Déjame entrar'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=15D2podGiC4S83OrrAG1Wgz98ZCvpBXAx' WHERE title = 'Diario de una Ninfómana'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1MKCo5iczNjDutfCrgmBNBKQlMHwREO8w' WHERE title = 'Drácula'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=160RyWkV3rsF4KJFh8EF9QLQT6Vz00pSv' WHERE title = 'Dune'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1-tev3BP7PE3e1Eiue2JZo1f8kIHNhHQo' WHERE title = 'El mesías de Dune'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1Hu2BREwlnejgkN9rTFVlT2dr-s8c6TUI' WHERE title = 'Hijos de Dune'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1akedJZyJulrDO9GGxweoQiYM3Hk3ICYc' WHERE title = 'Dios emperador de Dune'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1bdznCVM9LOfE5WyUG1Jqfm1e_-mL3KD5' WHERE title = 'Herejes de Dune'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1-QKnFPEXXKvcHmb3wMKCwjd6Lu363OYl' WHERE title = 'Casa capitular Dune'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1ccp7sUV8grkX7PHqDQdiG-lA7Himkp_Y' WHERE title = 'Cazadores de Dune'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1Lzo-7g4Yce36pjFms3IwTlL4F30ma-jQ' WHERE title = 'Gusanos de arena de Dune'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1aZNq1trlmZGtOl8H4ALUCuTlZQzZhqKB' WHERE title = 'El Aliento de los dioses'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1QUCZH2PPejT1saZ2KwHfKG7Rnh6Px5Wk' WHERE title = 'El Alquimista'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1SqEGedFPIcVf_ScXqzhX9Qaoo0AA0S5J' WHERE title = 'El cazador'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1BlOz7z_7n0rv51aYBc9j6-4XpA6dy3CP' WHERE title = 'La tormenta'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1Za_dw5WYHSAdywy3cqFW402stqvCHcww' WHERE title = 'El emperador'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1n9m_DL6_dy20YGINpQSPycnkOsNrXDuM' WHERE title = 'Ángeles y Demonios'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1wua6d7GUvxQ_ZpLVX41UWIxt5CfXbMiu' WHERE title = 'El código Da Vinci'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1okxIoF8-hfiV__m1ZIQJdybPt4GnmrBj' WHERE title = 'El símbolo perdido'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1rAM0XGJk74ZlYhjo_1fLvnzLgno6nX23' WHERE title = 'Inferno'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=19UC4i_CxYhNHSZCCEITKnHa4HaqUKYrY' WHERE title = 'Origen'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1vHlZ7xpveT2x4J5BRrD3o3Fo41nEFEfO' WHERE title = 'El cuento de la criada'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1ZMGVaoLK6Ush46t0ZTh9Ixv7ltKmyuZc' WHERE title = 'El exorcista'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1JmsXvMTo1K3RzLmUO9MPogzj6QJpclyq' WHERE title = 'El juego de Ender'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1bpyjeXKG8-tgb1haLatPmFEJkocyKMyM' WHERE title = 'La voz de los muertos'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1YXYVz0R2gcqb4OykA6J0rnjDg3E93dZ2' WHERE title = 'Ender el xenocida'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1CYR8x9W5RgYrhrUCAwXode5HyLk6Sb-6' WHERE title = 'Hijos de la mente'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1pXn5RgQljqp9zFjdhJoG62lWDVNy4bZS' WHERE title = 'Ender en el exilio'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1jM01AEEwvRAtyKHGvPWxV4AQx8PX1CBT' WHERE title = 'El nuevo Kamasutra ilustrado'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=18Vbn8MjP9YcwoIXUTqCh6ltG2xlXqNFQ' WHERE title = 'El psicoanalista'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1MnyCi8DIveSNvp6hvubyii-Jl5-DwZsu' WHERE title = 'Jaque al psicoanalista'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1ikbHSc1SvAZZ0rMV6EHsMwN30d6rjYVt' WHERE title = 'El psicoanalista en la mira'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1bSQgQoKUOHAOro-jk0WGGiX8bOnMwVTZ' WHERE title = 'El resplandor'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1jlohbvZQN4e9eLzYDBX7RhYrWA7_xxzp' WHERE title = 'Doctor sueño'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=13kR7SF_rv6bwxGXeEBq-QvvrGx4OCUtQ' WHERE title = 'El señor de los anillos'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1ZjlbmV1q5lWtCjkx3jQ9irbdtrCKq_mF' WHERE title = 'La comunidad del anillo'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=11PwAx47be127tVwzGrR6c3U8ZWZYXcCV' WHERE title = 'Las dos torres'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1NZQqbRRv7UOUR3EcML2i5vnEQTct_-LT' WHERE title = 'El retorno del rey'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=196JYMoGEs4ZNMhxDewdLfujAWwUK2eCk' WHERE title = 'El show de las marionetas'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1TKh7luQWFrfOcOgmuK1xZjDZKXxGQHe0' WHERE title = 'Hannibal el origen del mal'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1nv0YVvnV2PENphSC2cqD9EtmVEfzYACE' WHERE title = 'Dragón Rojo'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1s4iIEsQzoU5DuFZGfj7iow1qZN4BaWVi' WHERE title = 'El silencio de los corderos'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1o3O5wDBPXcvTZcThSPN6mMdzpWpIy5e8' WHERE title = 'Hannibal'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=142OKzgkmux34jxdWQC3mIYG00keRzLFJ' WHERE title = 'La defensa del Eliseo'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1Uv5u3xng21vhZFNJPOTLNidFklaKb26Z' WHERE title = 'En las montañas de la locura'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1wLcrFAqTw63SrQOoGvRHafo-JVjgVOSo' WHERE title = 'Fahreinheit 451'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=16aFF1PS5223WD_WG_Z0ja2LTTFYt1hD0' WHERE title = 'Frankenstein'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1dZanG6458ygv0e8Lx3VC0uuiP7tvuw7X' WHERE title = 'Guerra mundial Z'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1UH45L_HJW9mhbhA-qnMIH82bsLlmUAHW' WHERE title = 'La Cala'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1JPOaOlBozr2TH99wSXGry8VsRJcVPO8v' WHERE title = 'Haunting Adeline: Nunca te dejaré'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1GKyFqEOZdpQ8694PDuXwvvv0xSgUojE0' WHERE title = 'Te encontraré'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1MxZfskv7lmDQNkATqz6JQbuKYrS2uliZ' WHERE title = 'La biblia contada para escépticos'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1qhRkTvop4Vy74OhrmwMUm6mYSew4wkCm' WHERE title = 'La cúpula'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=10ESTpi9a_SWgAUE7CaD2q0SmlhRuCAC7' WHERE title = 'La enfermera de Auschwitz'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1Gicfe2gA-_MXxRdQR-B9aGSqdbxD_fbX' WHERE title = 'La guerra de los mundos'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1Q-JDlir6w9tD1iNy0B5BDcVh517IJHJ-' WHERE title = 'La llamada de Cthulhu'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1l564v936X2h-YXn_SgpzpbAcSbzNOIyL' WHERE title = 'La historia interminable'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1dztF51qJwm8HzNpIsiggp4YwZ9GmT7wa' WHERE title = 'Lascivia Pecados placenteros'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1uVmsUA8rsWLW7XQf0EQQoIUbBbvNbsh5' WHERE title = 'Lolita'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1KuuDbTrWwvz3LujQ4Ng5I7SoDPMZm-wv' WHERE title = 'Las edades de Lulú'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1076hu52P4RLDPM4YpFGgorD11AdcZ8We' WHERE title = 'Moby Dick'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1ax23AELQx38fLxDqYoLxHVafaWhSaOJX' WHERE title = 'La tapadera'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=13iS9Ui7ZUD8_VSjeviSIc5MvTaFXemTO' WHERE title = 'El intercambio'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1rRlNMxIf-gTQT783JqHUZJNYfHo014rw' WHERE title = 'Soy Leyenda'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1vrC3fa3JbQRgfxNxo_tTxYaBCz7yv6QX' WHERE title = 'Trenza del Mar esmeralda'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1GLttZZJjR26m9uizz2E_LbNlgqhCKKRz' WHERE title = 'Un crimen invisible'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1wwJprXjK7SB2MdjVxM8vIhpy6sQTueAS' WHERE title = 'Un crimen imaginado'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1K6urrhqckk63sHcOTjMP5c1SuMTWi0u2' WHERE title = 'Un crimen contratado'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1YXHWFprxOKLXrIabp-L0xsp7-aUMV3IW' WHERE title = 'Un crimen pasional'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1HAnIOmTOSQBjo5USY9uZlbg7PIxU-FZh' WHERE title = 'Un crimen prescrito'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=14mpj02BN-0FSIMxqHx5hH5NHPd7mAPOb' WHERE title = 'Un crimen vengado'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=13xgQ-dLUdVCPPqIZGuk4Kfs2OQngsQG-' WHERE title = 'Susurros sensuales'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=176dMBLFJKq9DRsOaJBqmajibKyPL4Q8-' WHERE title = 'Yo, robot'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1TapBb4d6yclySs9oNaW51MsOUO8XdXYY' WHERE title = 'Bóvedas de acero'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=19yO588yJj0t8Cs9kVlT8KfTwXhCXEyUD' WHERE title = 'El Sol desnudo'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1RFg-tmc9_ukjR64rZxvZkxyImHceTIbo' WHERE title = 'Los Robots del amanecer'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1oqqj2CclTGEnRlFY5ZIerFOauOkJO9TW' WHERE title = 'Robots e imperio'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1BseVzvLVdUeFadq7Krgoa4u8N-LimqFN' WHERE title = 'Yumi y el pintor de pesadillas'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1dxT1D4M6imyal8VyK6eN_BUcHmldl7_C' WHERE title = 'La rueda del tiempo'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1IhUu-N2qbRK62SuUUh1-s07kQGOw_vef' WHERE title = 'El Imperio Final'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1bl8aWT1T9PItuvCe8OjTq-3K5Um2G5X9' WHERE title = 'El pozo de ascensión'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1KyHh5IOON-PiXjXSDYy4_vbG_Cr6Flk8' WHERE title = 'El Héroe de las eras'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1OTU3Ap6_eROnVwQWG1SNIAtxb91L5s7y' WHERE title = 'Aleación de ley'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1DCKg6ciI1kAWCAEiIof2U8X7AsUbvzJL' WHERE title = 'Sombras de identidad'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1Uiy5bmrwlXgHVK2amWlmaqv1ZsDZzYCs' WHERE title = 'Brazales de duelo'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1ZxItejo7qIHtRM0Wrh73uBGa9OIN5jbq' WHERE title = 'Historia secreta'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1tpVSr2kUwk9c93ii02w6FYbulaG2iofa' WHERE title = 'El metal perdido'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1MhCsfZimrQnu_JwViyN6eFpxIxViaV8q' WHERE title = 'Pídeme lo que quieras'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1vSIRZhXv-LjsjHmyWI5r3qWf7PyyisCU' WHERE title = 'Pídeme lo que quieras, ahora y siempre'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1uMuEWBpjiVGnQOvrisKpdROsVtYB4OY9' WHERE title = 'Pídeme lo que quieras o déjame'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1zLaPyfhuyQCWBWSklWopLVDeVEqh9MBW' WHERE title = 'Pídeme lo que quieras y yo te lo daré'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=13MbDkq_UTOciSaw0ejJ4wNSgk3-FMd1z' WHERE title = 'La chica del tren'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1NfzbLAsmdAzwnU6H4C3bSUnIJm4ZRBp_' WHERE title = 'Sistemas críticos'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1BtX30ZQ2NF8AMFMOOFDviEUSHwaA708a' WHERE title = 'Condición artificial'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1GMuQA5f3eYKzi7wdKkymDtleLwrp5XD-' WHERE title = 'Harry Potter y la piedra filosofal'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1NTt_lMgwtlr1g1qsfW7hyF0DVdHcR7UP' WHERE title = 'Harry Potter y la cámara secreta'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1ayvGGq7NyweKsFZC2RfPDOjqRHWX2XpX' WHERE title = 'Harry Potter y el prisionero de Azkaban'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1PWSb59HVm609bch-B79qrZkVDWVrdE06' WHERE title = 'Harry Potter y el cáliz de fuego'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1cHgyt6fneyzthPqi4G1BX-2E3YN2rtm_' WHERE title = 'Harry Potter y la orden del Fénix'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1zUdJJjR7s-JesfzqaQsO-ZcCTMpnmdRY' WHERE title = 'Harry Potter y el misterio del príncipe'",
        "UPDATE `documents` SET url_image = 'https://drive.google.com/uc?export=download&id=1qbIcvV2M3dTT7tquLCziFeKddsXKaY1N' WHERE title = 'Harry Potter y las reliquias de la muerte'",
    ]
    for query in queries:     
        cursor.execute(query)
    pass

def downgrade(cursor):
    # Aquí va el código para revertir la migración
    cursor.execute()
    pass
