# migrations/20250516_194652_insert_urldocument_documents.py


# Migración: insert_urldocument_documents
# Fecha de creación: 20250516_194652


def upgrade(cursor):
    # Aquí va el código para aplicar la migración
    queries = [
        "UPDATE `documents` SET url_document = 'books/american_psycho.epub' WHERE title = 'American Psycho'",
        "UPDATE `documents` SET url_document = 'books/arcanum_ilimitado.epub' WHERE title = 'Arcanum ilimitado'",
        "UPDATE `documents` SET url_document = 'books/battle_royale.epub' WHERE title = 'Battle Royale'",
        "UPDATE `documents` SET url_document = 'books/elantris.epub' WHERE title = 'Elantris'",
        "UPDATE `documents` SET url_document = 'books/escuadron_escuadron.epub' WHERE title = 'Escuadrón'",
        "UPDATE `documents` SET url_document = 'books/escuadron_estelar.epub' WHERE title = 'Estelar'",
        "UPDATE `documents` SET url_document = 'books/escuadron_citonica.epub' WHERE title = 'Citónica'",
        "UPDATE `documents` SET url_document = 'books/escuadron_desafiante.epub' WHERE title = 'Desafiante'",
        "UPDATE `documents` SET url_document = 'books/el_archivo_de_las_tormentas_el_camino_de_los_reyes.epub' WHERE title = 'El camino de los reyes'",
        "UPDATE `documents` SET url_document = 'books/el_archivo_de_las_tormentas_palabras_radiantes.epub' WHERE title = 'Palabras Radiantes'",
        "UPDATE `documents` SET url_document = 'books/el_archivo_de_las_tormentas_danzante_del_filo.epub' WHERE title = 'Danzante del Filo'",
        "UPDATE `documents` SET url_document = 'books/el_archivo_de_las_tormentas_juramentada.epub' WHERE title = 'Juramentada'",
        "UPDATE `documents` SET url_document = 'books/el_archivo_de_las_tormentas_esquirla_del_amanecer.epub' WHERE title = 'Esquirla del amanecer'",
        "UPDATE `documents` SET url_document = 'books/el_archivo_de_las_tormentas_el_ritmo_de_la_guerra.epub' WHERE title = 'El ritmo de la guerra'",
        "UPDATE `documents` SET url_document = 'books/el_archivo_de_las_tormentas_el_hombre_iluminado.epub' WHERE title = 'El hombre iluminado'",
        "UPDATE `documents` SET url_document = 'books/el_archivo_de_las_tormentas_viento_y_verdad.epub' WHERE title = 'Viento y Verdad'",
        "UPDATE `documents` SET url_document = 'books/50_sombras_de_grey.epub' WHERE title = '50 Sombras de Grey'",
        "UPDATE `documents` SET url_document = 'books/50_sombras_mas_oscuras.epub' WHERE title = '50 Sombras más oscuras'",
        "UPDATE `documents` SET url_document = 'books/50_sombras_liberadas.epub' WHERE title = '50 Sombras liberadas'",
        "UPDATE `documents` SET url_document = 'books/odisea_espacial_2001_una_odisea_espacial.epub' WHERE title = '2001 Una odisea espacial'",
        "UPDATE `documents` SET url_document = 'books/odisea_espacial_2010_odisea_dos.epub' WHERE title = '2010 Odisea dos'",
        "UPDATE `documents` SET url_document = 'books/odisea_espacial_2061_odisea_tres.epub' WHERE title = '2061 Odisea tres'",
        "UPDATE `documents` SET url_document = 'books/odisea_espacial_3001_odisea_final.epub' WHERE title = '3001 Odisea final'",
        "UPDATE `documents` SET url_document = 'books/apocalipsis_z_el_principio_del_fin.epub' WHERE title = 'El principio del fin'",
        "UPDATE `documents` SET url_document = 'books/apocalipsis_z_los_dias_oscuros.epub' WHERE title = 'Los dias oscuros'",
        "UPDATE `documents` SET url_document = 'books/apocalipsis_z_la_ira_de_los_justos.epub' WHERE title = 'La ira de los justos'",
        "UPDATE `documents` SET url_document = 'books/arena_blanca.epub' WHERE title = 'Arena blanca'",
        "UPDATE `documents` SET url_document = 'books/ascension.epub' WHERE title = 'Ascensión'",
        "UPDATE `documents` SET url_document = 'books/asesinato_en_el_orient_express.epub' WHERE title = 'Asesinato en el Orient express'",
        "UPDATE `documents` SET url_document = 'books/cancion_de_hielo_y_fuego_juego_de_tronos.epub' WHERE title = 'Juego de tronos'",
        "UPDATE `documents` SET url_document = 'books/cancion_de_hielo_y_fuego_choque_de_reyes.epub' WHERE title = 'Choque de Reyes'",
        "UPDATE `documents` SET url_document = 'books/cancion_de_hielo_y_fuego_tormenta_de_espadas.epub' WHERE title = 'Tormenta de espadas'",
        "UPDATE `documents` SET url_document = 'books/cancion_de_hielo_y_fuego_festin_de_cuervos.epub' WHERE title = 'Festín de cuervos'",
        "UPDATE `documents` SET url_document = 'books/cancion_de_hielo_y_fuego_danza_de_dragones.epub' WHERE title = 'Danza de Dragones'",
        "UPDATE `documents` SET url_document = 'books/carrie.epub' WHERE title = 'Carrie'",
        "UPDATE `documents` SET url_document = 'books/cujo.epub' WHERE title = 'Cujo'",
        "UPDATE `documents` SET url_document = 'books/dejame_entrar.epub' WHERE title = 'Déjame entrar'",
        "UPDATE `documents` SET url_document = 'books/diario_de_una_ninfomana.epub' WHERE title = 'Diario de una Ninfómana'",
        "UPDATE `documents` SET url_document = 'books/dracula.epub' WHERE title = 'Drácula'",
        "UPDATE `documents` SET url_document = 'books/dune.epub' WHERE title = 'Dune'",
        "UPDATE `documents` SET url_document = 'books/dune_el_mesias_de_dune.epub' WHERE title = 'El mesías de Dune'",
        "UPDATE `documents` SET url_document = 'books/dune_hijos_de_dune.epub' WHERE title = 'Hijos de Dune'",
        "UPDATE `documents` SET url_document = 'books/dune_dios_emperador_de_dune.epub' WHERE title = 'Dios emperador de Dune'",
        "UPDATE `documents` SET url_document = 'books/dune_herejes_de_dune.epub' WHERE title = 'Herejes de Dune'",
        "UPDATE `documents` SET url_document = 'books/dune_casa_capitular_dune.epub' WHERE title = 'Casa capitular Dune'",
        "UPDATE `documents` SET url_document = 'books/dune_cazadores_de_dune.epub' WHERE title = 'Cazadores de Dune'",
        "UPDATE `documents` SET url_document = 'books/dune_gusanos_de_arena_de_dune.epub' WHERE title = 'Gusanos de arena de Dune'",
        "UPDATE `documents` SET url_document = 'books/el_aliento_de_los_dioses.epub' WHERE title = 'El Aliento de los dioses'",
        "UPDATE `documents` SET url_document = 'books/el_alquimista.epub' WHERE title = 'El Alquimista'",
        "UPDATE `documents` SET url_document = 'books/dark_verse_el_cazador.epub' WHERE title = 'El cazador'",
        "UPDATE `documents` SET url_document = 'books/dark_verse_la_tormenta.epub' WHERE title = 'La tormenta'",
        "UPDATE `documents` SET url_document = 'books/dark_verse_el_emperador.epub' WHERE title = 'El emperador'",
        "UPDATE `documents` SET url_document = 'books/robert_langdon_angeles_y_demonios.epub' WHERE title = 'Ángeles y Demonios'",
        "UPDATE `documents` SET url_document = 'books/robert_langdon_el_codigo_da_vinci.epub' WHERE title = 'El código Da Vinci'",
        "UPDATE `documents` SET url_document = 'books/robert_langdon_el_simbolo_perdido.epub' WHERE title = 'El símbolo perdido'",
        "UPDATE `documents` SET url_document = 'books/robert_langdon_inferno.epub' WHERE title = 'Inferno'",
        "UPDATE `documents` SET url_document = 'books/robert_langdon_origen.epub' WHERE title = 'Origen'",
        "UPDATE `documents` SET url_document = 'books/el_cuento_de_la_criada.epub' WHERE title = 'El cuento de la criada'",
        "UPDATE `documents` SET url_document = 'books/el_exorcista.epub' WHERE title = 'El exorcista'",
        "UPDATE `documents` SET url_document = 'books/saga_de_ender_el_juego_de_ender.epub' WHERE title = 'El juego de Ender'",
        "UPDATE `documents` SET url_document = 'books/saga_de_ender_la_voz_de_los_muertos.epub' WHERE title = 'La voz de los muertos'",
        "UPDATE `documents` SET url_document = 'books/saga_de_ender_ender_el_xenocida.epub' WHERE title = 'Ender el xenocida'",
        "UPDATE `documents` SET url_document = 'books/saga_de_ender_hijos_de_la_mente.epub' WHERE title = 'Hijos de la mente'",
        "UPDATE `documents` SET url_document = 'books/saga_de_ender_ender_en_el_exilio.epub' WHERE title = 'Ender en el exilio'",
        "UPDATE `documents` SET url_document = 'books/el_nuevo_kamasutra_ilustrado.epub' WHERE title = 'El nuevo Kamasutra ilustrado'",
        "UPDATE `documents` SET url_document = 'books/el_psicoanalista.epub' WHERE title = 'El psicoanalista'",
        "UPDATE `documents` SET url_document = 'books/el_psicoanalista_jaque_al_psicoanalista.epub' WHERE title = 'Jaque al psicoanalista'",
        "UPDATE `documents` SET url_document = 'books/el_psicoanalista_el_psicoanalista_en_la_mira.epub' WHERE title = 'El psicoanalista en la mira'",
        "UPDATE `documents` SET url_document = 'books/el_resplandor.epub' WHERE title = 'El resplandor'",
        "UPDATE `documents` SET url_document = 'books/el_resplandor_doctor_sueño.epub' WHERE title = 'Doctor sueño'",
        "UPDATE `documents` SET url_document = 'books/el_senor_de_los_anillos.epub' WHERE title = 'El señor de los anillos'",
        "UPDATE `documents` SET url_document = 'books/el_senor_de_los_anillos_la_comunidad_del_anillo.epub' WHERE title = 'La comunidad del anillo'",
        "UPDATE `documents` SET url_document = 'books/el_senor_de_los_anillos_las_dos_torres.epub' WHERE title = 'Las dos torres'",
        "UPDATE `documents` SET url_document = 'books/el_senor_de_los_anillos_el_retorno_del_rey.epub' WHERE title = 'El retorno del rey'",
        "UPDATE `documents` SET url_document = 'books/el_show_de_las_marionetas.epub' WHERE title = 'El show de las marionetas'",
        "UPDATE `documents` SET url_document = 'books/hannibal_lecter_hannibal_el_origen_del_mal.epub' WHERE title = 'Hannibal el origen del mal'",
        "UPDATE `documents` SET url_document = 'books/hannibal_lecter_dragon_rojo.epub' WHERE title = 'Dragón Rojo'",
        "UPDATE `documents` SET url_document = 'books/hannibal_el_silencio_de_los_corderos.epub' WHERE title = 'El silencio de los corderos'",
        "UPDATE `documents` SET url_document = 'books/hannibal_lecter_hannibal.epub' WHERE title = 'Hannibal'",
        "UPDATE `documents` SET url_document = 'books/en_defensa_del_eliseo.epub' WHERE title = 'En defensa del Eliseo'",
        "UPDATE `documents` SET url_document = 'books/en_las_montanas_de_la_locura.epub' WHERE title = 'En las montañas de la locura'",
        "UPDATE `documents` SET url_document = 'books/fahrenheit_451.epub' WHERE title = 'Fahreinheit 451'",
        "UPDATE `documents` SET url_document = 'books/frankenstein.epub' WHERE title = 'Frankenstein'",
        "UPDATE `documents` SET url_document = 'books/guerra_mundial_z.epub' WHERE title = 'Guerra mundial Z'",
        "UPDATE `documents` SET url_document = 'books/la_cala.epub' WHERE title = 'La Cala'",
        "UPDATE `documents` SET url_document = 'books/dueto_del_gato_y_el_ratón_haunting_Adeline.epub' WHERE title = 'Haunting Adeline: Nunca te dejaré'",
        "UPDATE `documents` SET url_document = 'books/dueto_del_gato_y_el_ratón_te_encontraré.epub' WHERE title = 'Te encontraré'",
        "UPDATE `documents` SET url_document = 'books/la_biblia_contada_para_escepticos.epub' WHERE title = 'La biblia contada para escépticos'",
        "UPDATE `documents` SET url_document = 'books/la_cupula.epub' WHERE title = 'La cúpula'",
        "UPDATE `documents` SET url_document = 'books/la_enfermera_de_auschwitz.epub' WHERE title = 'La enfermera de Auschwitz'",
        "UPDATE `documents` SET url_document = 'books/la_guerra_de_los_mundos.epub' WHERE title = 'La guerra de los mundos'",
        "UPDATE `documents` SET url_document = 'books/la_llamada_de_cthulhu.epub' WHERE title = 'La llamada de Cthulhu'",
        "UPDATE `documents` SET url_document = 'books/la_historia_interminable.epub' WHERE title = 'La historia interminable'",
        "UPDATE `documents` SET url_document = 'books/lascivia_pecados_placenteros.epub' WHERE title = 'Lascivia Pecados placenteros'",
        "UPDATE `documents` SET url_document = 'books/lolita.epub' WHERE title = 'Lolita'",
        "UPDATE `documents` SET url_document = 'books/las_edades_de_lulu.epub' WHERE title = 'Las edades de Lulú'",
        "UPDATE `documents` SET url_document = 'books/moby_dick.epub' WHERE title = 'Moby Dick'",
        "UPDATE `documents` SET url_document = 'books/la_tapadera_la_tapadera.epub' WHERE title = 'La tapadera'",
        "UPDATE `documents` SET url_document = 'books/la_tapadera_el_intercambio.epub' WHERE title = 'El intercambio'",
        "UPDATE `documents` SET url_document = 'books/soy_leyenda.epub' WHERE title = 'Soy Leyenda'",
        "UPDATE `documents` SET url_document = 'books/trenza_del_mar_esmeralda.epub' WHERE title = 'Trenza del Mar esmeralda'",
        "UPDATE `documents` SET url_document = 'books/crimenes_imperceptibles_un_crimen_invisible.epub' WHERE title = 'Un crimen invisible'",
        "UPDATE `documents` SET url_document = 'books/crimenes_imperceptibles_un_crimen_imaginado.epub' WHERE title = 'Un crimen imaginado'",
        "UPDATE `documents` SET url_document = 'books/crimenes_imperceptibles_un_crimen_contratado.epub' WHERE title = 'Un crimen contratado'",
        "UPDATE `documents` SET url_document = 'books/crimenes_imperceptibles_un_crimen_pasional.epub' WHERE title = 'Un crimen pasional'",
        "UPDATE `documents` SET url_document = 'books/crimenes_imperceptibles_un_crimen_prescrito.epub' WHERE title = 'Un crimen prescrito'",
        "UPDATE `documents` SET url_document = 'books/' WHERE title = 'Un crimen vengado'",
        "UPDATE `documents` SET url_document = 'books/susurros_sensuales.epub' WHERE title = 'Susurros sensuales'",
        "UPDATE `documents` SET url_document = 'books/serie_de_los_robots_yo_robot.epub' WHERE title = 'Yo, robot'",
        "UPDATE `documents` SET url_document = 'books/serie_de_los_robots_bovedas_de_acero.epub' WHERE title = 'Bóvedas de acero'",
        "UPDATE `documents` SET url_document = 'books/serie_de_los_robots_el_sol_desnudo.epub' WHERE title = 'El Sol desnudo'",
        "UPDATE `documents` SET url_document = 'books/serie_de_los_robots_los_robots_del_amanecer.epub' WHERE title = 'Los Robots del amanecer'",
        "UPDATE `documents` SET url_document = 'books/serie_de_los_robots_robots_e_imperio.epub' WHERE title = 'Robots e imperio'",
        "UPDATE `documents` SET url_document = 'books/yumi_y_el_pintor_de_pesadillas.epub' WHERE title = 'Yumi y el pintor de pesadillas'",
        "UPDATE `documents` SET url_document = 'books/la_rueda_del_tiempo.epub' WHERE title = 'La rueda del tiempo'",
        "UPDATE `documents` SET url_document = 'books/nacidos_de_la_bruma_el_imperio_final.epub' WHERE title = 'El Imperio Final'",
        "UPDATE `documents` SET url_document = 'books/nacidos_de_la_bruma_el_pozo_de_ascension.epub' WHERE title = 'El pozo de ascensión'",
        "UPDATE `documents` SET url_document = 'books/nacidos_de_la_bruma_el_heroe_de_las_eras.epub' WHERE title = 'El Héroe de las eras'",
        "UPDATE `documents` SET url_document = 'books/nacidos_de_la_bruma_aleacion_de_ley.epub' WHERE title = 'Aleación de ley'",
        "UPDATE `documents` SET url_document = 'books/nacidos_de_la_bruma_sombras_de_identidad.epub' WHERE title = 'Sombras de identidad'",
        "UPDATE `documents` SET url_document = 'books/nacidos_de_la_bruma_brazales_de_duelo.epub' WHERE title = 'Brazales de duelo'",
        "UPDATE `documents` SET url_document = 'books/nacidos_de_la_bruma_historia_secreta.epub' WHERE title = 'Historia secreta'",
        "UPDATE `documents` SET url_document = 'books/nacidos_de_la_bruma_el_metal_perdido.epub' WHERE title = 'El metal perdido'",
        "UPDATE `documents` SET url_document = 'books/pideme_lo_que_quieras' WHERE title = 'Pídeme lo que quieras'",
        "UPDATE `documents` SET url_document = 'books/pideme_lo_que_quieras_pideme_lo_que_quieras_ahora_y_siempre.epub' WHERE title = 'Pídeme lo que quieras, ahora y siempre'",
        "UPDATE `documents` SET url_document = 'books/pideme_lo_que_quieras_pideme_lo_que_quieras_o_dejame.epub' WHERE title = 'Pídeme lo que quieras o déjame'",
        "UPDATE `documents` SET url_document = 'books/pideme_lo_que_quieras_pideme_lo_que_quieras_y_yo_te_lo_dare.epub' WHERE title = 'Pídeme lo que quieras y yo te lo daré'",
        "UPDATE `documents` SET url_document = 'books/la_chica_del_tren.epub' WHERE title = 'La chica del tren'",
        "UPDATE `documents` SET url_document = 'books/murderbot_sistemas_criticos.epub' WHERE title = 'Sistemas críticos'",
        "UPDATE `documents` SET url_document = 'books/murderbot_condicion_artificial.epub' WHERE title = 'Condición artificial'",
        "UPDATE `documents` SET url_document = 'books/harry_potter_y_la_piedra_filosofal.epub' WHERE title = 'Harry Potter y la piedra filosofal'",
        "UPDATE `documents` SET url_document = 'books/harry_potter_y_la_camara_secreta.epub' WHERE title = 'Harry Potter y la cámara secreta'",
        "UPDATE `documents` SET url_document = 'books/harry_potter_y_el_prisionero_de_azkaban.epub' WHERE title = 'Harry Potter y el prisionero de Azkaban'",
        "UPDATE `documents` SET url_document = 'books/harry_potter_y_el_caliz_de_fuego.epub' WHERE title = 'Harry Potter y el cáliz de fuego'",
        "UPDATE `documents` SET url_document = 'books/harry_potter_y_la_orden_del_fenix.epub' WHERE title = 'Harry Potter y la orden del Fénix'",
        "UPDATE `documents` SET url_document = 'books/harry_potter_y_el_misterio_del_principe.epub' WHERE title = 'Harry Potter y el misterio del príncipe'",
        "UPDATE `documents` SET url_document = 'books/harry_potter_y_las_reliquias_de_la_muerte.epub' WHERE title = 'Harry Potter y las reliquias de la muerte'",
    ]

    for query in queries:
        cursor.execute(query)
    pass


def downgrade(cursor):
    # Aquí va el código para revertir la migración
    cursor.execute()
    pass
