-- CREACION DE LA BASE DE DATOS
CREATE DATABASE bibliapp
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

-- USO DE LA BASE DE DATOS
USE bibliapp;

-- CREACION DE LAS TABLAS
CREATE TABLE users (
    user_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    auth_token VARCHAR(255) DEFAULT NULL,
    role VARCHAR(20) DEFAULT 'user',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE documents (
    document_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    publication_year INT NOT NULL,
    document_type VARCHAR(50) NOT NULL,
    num_pages INT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    synopsis TEXT,
    url_image VARCHAR(255),
    url_document VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE registers (
    register_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    document_id INT NOT NULL,
    favorite BOOLEAN DEFAULT FALSE,
    readed BOOLEAN DEFAULT FALSE,
    progress INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (user_id) REFERENCES users(user_id)
    ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (document_id) REFERENCES documents(document_id)
    ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE notes (
    note_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    register_id INT NOT NULL,
    note TEXT NOT NULL,
    page INT NOT NULL,
    coord_x INT NOT NULL,
    coord_y INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (register_id) REFERENCES registers(register_id)
    ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE categories (
    id_category INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    id_document INT NOT NULL,
    name VARCHAR(50) NOT NULL UNIQUE,

    FOREIGN KEY (id_document) REFERENCES documents(document_id)
    ON DELETE RESTRICT ON UPDATE CASCADE
);