CREATE DATABASE bibliapp
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

USE bibliapp;

CREATE TABLE users (
    user_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_name VARCHAR(50) NOT NULL,
    user_lastname VARCHAR(50) NOT NULL,
    username VARCHAR(30) NOT NULL UNIQUE,
    email VARCHAR(50) NOT NULL UNIQUE,
    user_password VARCHAR(60) NOT NULL,
    user_role VARCHAR(10) DEFAULT 'user',
    user_sub INT(2) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE tokens (
    token_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    token TEXT NOT NULL,
    device VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    expires_at DATETIME NOT NULL,
    FOREIGN KEY (username) REFERENCES users(username)
    ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE documents (
    document_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    publication_year INT NOT NULL,
    document_type VARCHAR(50) NOT NULL,
    num_pages INT NOT NULL,
    prequel INT(2),
    sequel INT(2),
    synopsis TEXT,
    price DECIMAL(10, 2) NOT NULL,
    category_1 VARCHAR(25) NOT NULL,
    category_2 VARCHAR(25),
    url_image VARCHAR(255),
    url_document VARCHAR(255),
    slug VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE registers (
    register_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username INT NOT NULL,
    document_id INT NOT NULL,
    favorite BOOLEAN DEFAULT FALSE,
    readed BOOLEAN DEFAULT FALSE,
    progress INT(3) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (username) REFERENCES users(username)
    ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (document_id) REFERENCES documents(document_id)
    ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE notes (
    note_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    register_id INT NOT NULL,
    note TEXT NOT NULL,
    note_page INT NOT NULL,
    coord_x INT NOT NULL,
    coord_y INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (register_id) REFERENCES registers(register_id)
    ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE categories (
    category_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    document_id INT NOT NULL,
    category_name VARCHAR(50) NOT NULL UNIQUE,

    FOREIGN KEY (document_id) REFERENCES documents(document_id)
    ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS migrations (
    migration_id INT AUTO_INCREMENT PRIMARY KEY,
    filename VARCHAR(255) NOT NULL UNIQUE,
    applied_at DATETIME DEFAULT CURRENT_TIMESTAMP
);